apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: shiojiri-rainbow-seeker
type: Opaque
stringData:
  # Database Configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "shiojiri_rainbow"
  DB_USER: "postgres"
  DB_PASSWORD: "REPLACE_WITH_ACTUAL_PASSWORD"
  
  # JWT Configuration
  JWT_SECRET: "REPLACE_WITH_ACTUAL_JWT_SECRET"
  
  # Weather API Configuration
  WEATHER_API_KEY: "REPLACE_WITH_ACTUAL_WEATHER_API_KEY"
  
  # Firebase Configuration
  FIREBASE_PROJECT_ID: "REPLACE_WITH_ACTUAL_PROJECT_ID"
  FIREBASE_CLIENT_EMAIL: "REPLACE_WITH_ACTUAL_CLIENT_EMAIL"
  FIREBASE_PRIVATE_KEY: "REPLACE_WITH_ACTUAL_PRIVATE_KEY"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "REPLACE_WITH_ACTUAL_REDIS_PASSWORD"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: shiojiri-rainbow-seeker
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  MODEL_PATH: "/app/models"
  PREDICTION_THRESHOLD: "0.5"